### PR TITLE
add suport for parsing files containing async/await

### PR DESCRIPTION
**Pull request by ifrim**
add suport for parsing files containing async/await, at the same time added support for overwriting/adding options to acorn

### CODE REVIEW

**Comment by mattdesl** [comment]
Cool! Is there any way we can 'opt-in' to the plugin only when the user calls the function with that option? I don't like writing modules or functions that have side-effects like this since it tends to create big problems down the road.

**Comment by mattdesl** [comment]
p.s. Thanks for the PR! :smile:

**Comment by ifrim** [comment]
Yes, maybe we can have acorn plugins installed separately and expose a callback that we pass the acorn instance to so that the plugins can be applied externally.

I'll have a look at this at work on monday. 

What do you think?

**Comment by ifrim** [comment]
Hi Matt,

I exposed two methods called "applyAcornPlugins" and "addAcornWalkBaseElementTypes". 

The first method, "applyAcornPlugins", allows for acorn plugins to be applied to the instance of acorn from the module. This way the module is not dependent on a specific set of acorn plugins. The plugins can be installed separately and applied externally in the callback. It should be future proof (it would be easy to apply future acorn plugins).

The second method, "addAcornWalkBaseElementTypes", adds node types that may be introduced by the applied acorn plugins. For example "acorn-jsx" adds "JSXElement" as a new node type and the acorn walker expects a function to call when it encounters this node type.

I tested using this code:

```
let detective = require('detect-import-require');
detective.applyAcornPlugins(function(acorn) {
    let newAcornInstance = acorn;
    newAcornInstance = require('acorn-es7-plugin')(newAcornInstance);
    newAcornInstance = require('acorn-jsx/inject')(newAcornInstance);
    return newAcornInstance;
});
detective.addAcornWalkBaseElementTypes(['JSXElement']);

let src = 'import \'./bbb\'; async function myfn() { return 1; } ReactDOM.render(<div></div>, document.getElementById(\'abc\'))';
let requires = detective(src, {
    acornOptions: {
        ecmaVersion: 7,
        plugins: {
            asyncawait: true,
            jsx: true
        }
    }
});

console.log(requires);
```

after I installed detect-import-require (the version containing this pull request), acorn-es7-plugin, and acorn-jsx

Please let me know if you want me to change anything (naming, code style, api) or we can discuss if you have a different approach.

Thanks!

**Comment by mattdesl** [comment]
Hmm, so I looked into it a bit more. Acorn does a weird thing with its plugins where they are all based around side-effects – so you can't "uninstall" a plugin, for example, and if two conflicting plugins are used with the same instance of acorn (which is very possible if you have a tree of modules that dedupe to the same instance in npm3) then you might run into problems.

I think the best approach to get JSX working with this module is to put the work on the end-user for them to call `acorn.parse`. This way they can use `acorn`, `acorn-jsx` or a completely custom fork of acorn with all their own options.

I've pushed some changes to 2.0.0 to support JSX, and I'm using a different module for walking the AST now which seems better with JSX nodes.

See here for how you can get JSX working now:
https://github.com/Jam3/detect-import-require/#custom-ast

Thanks again for bringing this to my attention! Hope this works for you. :smile:

**Comment by ifrim** [comment]
This seems much nicer. I'll give it a try. Thanks for the time. :)

**Pull request closed without merging**
